In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import r2_score

In [ ]:
df=pd.read_csv("mobile price prediction.csv")
df.head()

Unnamed: 0                         Brand me  Ratings  RAM    ROM  \
0           0            LG V30+ (Black, 128 )      4.3  4.0  128.0   
1           1                       I Kall K11      3.4  6.0   64.0   
2           2                     Nokia 105 ss      4.3  4.0    4.0   
3           3  Samsung Galaxy A50 (White, 64 )      4.4  6.0   64.0   
4           4       POCO F1 (Steel Blue, 128 )      4.5  6.0  128.0   

   Mobile_Size  Primary_Cam  Selfi_Cam  Battery_Power  Price  
0         6.00           48       13.0           4000  24999  
1         4.50           48       12.0           4000  15999  
2         4.50           64       16.0           4000  15000  
3         6.40           48       15.0           3800  18999  
4         6.18           35       15.0           3800  18999

In [ ]:
# Drop the Unwannted column the first one
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.head()

Brand me  Ratings  RAM    ROM  Mobile_Size  \
0            LG V30+ (Black, 128 )      4.3  4.0  128.0         6.00   
1                       I Kall K11      3.4  6.0   64.0         4.50   
2                     Nokia 105 ss      4.3  4.0    4.0         4.50   
3  Samsung Galaxy A50 (White, 64 )      4.4  6.0   64.0         6.40   
4       POCO F1 (Steel Blue, 128 )      4.5  6.0  128.0         6.18   

   Primary_Cam  Selfi_Cam  Battery_Power  Price  
0           48       13.0           4000  24999  
1           48       12.0           4000  15999  
2           64       16.0           4000  15000  
3           48       15.0           3800  18999  
4           35       15.0           3800  18999

In [ ]:
# Checking null values into the dataset
df.isnull().sum()

Brand me           0
Ratings           31
RAM                7
ROM                4
Mobile_Size        2
Primary_Cam        0
Selfi_Cam        269
Battery_Power      0
Price              0
dtype: int64

In [ ]:
# Dropping the Name columns
df.drop(['Brand me'],axis=1,inplace=True)

In [ ]:
# Fill up the mean values of all the missing value columns into the dataset
df['Ratings'] = df['Ratings'].fillna(df['Ratings'].mean())
df['RAM'] = df['RAM'].fillna(df['RAM'].mean())
df['ROM'] = df['ROM'].fillna(df['ROM'].mean())
df['Mobile_Size'] = df['Mobile_Size'].fillna(df['Mobile_Size'].mean())
df['Selfi_Cam'] = df['Selfi_Cam'].fillna(df['Selfi_Cam'].mean())

In [ ]:
# Changing the Datatype
df['RAM'] = df['RAM'].astype('int64')
df['ROM'] = df['ROM'].astype('int64')
df['Selfi_Cam'] = df['Selfi_Cam'].astype('int64')

In [ ]:
# Finding out the correlation between the features
corr = df.corr()
corr.shape

(8, 8)

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
X = df.iloc[:,1:7]  # Independent columns
y = df.iloc[:,[-1]] # Yarget column i.e price rang
# Apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=4)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
# Concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
featureScores

Specs          Score
0            RAM     605.009453
1            ROM   31222.209834
2    Mobile_Size     874.471349
3    Primary_Cam    1465.379223
4      Selfi_Cam    1358.898574
5  Battery_Power  156629.116310

In [ ]:
print(featureScores.nlargest(4,'Score'))  #print 5 best features

           Specs          Score
5  Battery_Power  156629.116310
1            ROM   31222.209834
3    Primary_Cam    1465.379223
4      Selfi_Cam    1358.898574


In [ ]:
# Fiting Feature Seclection using Ensemble Methods
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
model = ExtraTreesClassifier()
model.fit(X,y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


ExtraTreesClassifier()

In [ ]:
print(model.feature_importances_) #use inbuilt class feature_importances of tree based classifiers

[0.11938762 0.10390251 0.26648465 0.0856702  0.22506724 0.19948778]


In [ ]:
df.head()

Ratings  RAM  ROM  Mobile_Size  Primary_Cam  Selfi_Cam  Battery_Power  \
0      4.3    4  128         6.00           48         13           4000   
1      3.4    6   64         4.50           48         12           4000   
2      4.3    4    4         4.50           64         16           4000   
3      4.4    6   64         6.40           48         15           3800   
4      4.5    6  128         6.18           35         15           3800   

   Price  
0  24999  
1  15999  
2  15000  
3  18999  
4  18999

In [ ]:
# Value Assigning
X = df.iloc[:,[6,2,4,5,1,3]]
y = df.iloc[:,[-1]]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor()
reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor()

In [ ]:
y_pred = reg.predict(X_train)
# Training Score
print("Training Accuracy:",reg.score(X_train,y_train)*100)

Training Accuracy: 96.01662811704699


In [ ]:
# Testing Score
print("Testing Accuracy:",reg.score(X_test,y_test)*100)

Testing Accuracy: 95.07768162644872


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df.dtypes

Ratings          float64
RAM                int64
ROM                int64
Mobile_Size      float64
Primary_Cam        int64
Selfi_Cam          int64
Battery_Power      int64
Price              int64
dtype: object

In [ ]:
# Sample Prediction
reg.predict([[4.0,128,6,48,13,4000]])


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([171816.275])

In [ ]:
y_pred = reg.predict(X_test)
print("R^2 Score:",r2_score(y_test, y_pred)*100)

R^2 Score: 95.07768162644872


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

Mean Absolute Error: 3479.2633043612013
Mean Squared Error: 99510340.97643255


In [ ]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 9975.487004474146


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
y_pred = reg.predict(X_train)
# Training Score
print("Training Accuracy:",reg.score(X_train,y_train)*100)

Training Accuracy: 96.01662811704699


In [ ]:
# Testing Score
print("Testing Accuracy:",reg.score(X_test,y_test)*100)

Testing Accuracy: 95.07768162644872


In [ ]:
# Sample Prediction
reg.predict([[4.0,128,6,48,13,4000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([171816.275])

In [ ]:
y_pred = reg.predict(X_test)
print("R^2 Score:",r2_score(y_test, y_pred)*100)

R^2 Score: 95.07768162644872


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

Mean Absolute Error: 3479.2633043612013
Mean Squared Error: 99510340.97643255


In [ ]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 9975.487004474146


In [ ]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)
from sklearn.linear_model import LogisticRegression
logiReg = LogisticRegression().fit(X_train,y_train)
y_pred = logiReg.predict(X_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
# Sample Prediction
logiReg.predict([[4.0,128,6,48,13,4000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([970])

In [ ]:
y_pred = logiReg.predict(X_train)
# Training Score
print("Training Accuracy:",logiReg.score(X_train,y_train)*100)

Training Accuracy: 8.133971291866029


In [ ]:
reg.predict([[4.0,128,6,48,13,4000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([171816.275])

In [ ]:
print("Testing Accuracy:",logiReg.score(X_test,y_test)*100)

Testing Accuracy: 3.827751196172249


In [ ]:
y_pred = logiReg.predict(X_test)
print("R^2 Score:",r2_score(y_test, y_pred)*100)

R^2 Score: -13.297326285387934


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

Mean Absolute Error: 14085.593301435407
Mean Squared Error: 2290436073.9760766


In [ ]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 47858.50054040637


In [ ]:
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)
reg = LinearRegression().fit(X_train, y_train)
y_pred = reg.predict(X_train)

In [ ]:

y_pred = reg.predict(X_train)
# Training Score
print("Training Accuracy:",reg.score(X_train,y_train)*100)

Training Accuracy: 13.447453391804565


In [ ]:
# Sample Prediction
reg.predict([[4.0,128,6,48,13,4000]])

print("Testing Accuracy:",reg.score(X_test,y_test)*100)

Testing Accuracy: 11.58289517320542


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
print(X_train)

     Battery_Power  ROM  Primary_Cam  Selfi_Cam  RAM  Mobile_Size
780           1750   32           48         22    6         4.54
792           3000   16           48          8    1         4.50
297           1050   32           64          9    6         4.50
53            3800  128           48         12    6         6.39
267           5000  128           48          8    4         6.50
..             ...  ...          ...        ...  ...          ...
156           3000   64           48          8    6         4.50
384           2500   32           48          5    6         4.54
645           1050   64           64          9    8         4.50
757           3500   32           64          9    6         4.50
456           3000   12           48          5   12         4.54

[627 rows x 6 columns]


In [ ]:
print("X_test:",X_test.shape)
print("Y_test:",y_test.shape)
print("x_train:",X_train.shape)
print("y_train:",y_train.shape)

X_test: (209, 6)
Y_test: (209, 1)
x_train: (627, 6)
y_train: (627, 1)


In [ ]:
y_pred = reg.predict(X_test)
print("R^2 Score:",r2_score(y_test, y_pred)*100)

R^2 Score: 11.58289517320542


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

Mean Absolute Error: 18373.222540795407
Mean Squared Error: 1787453712.2058544


In [ ]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 42278.288898746294


In [ ]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(X_train,y_train)


Lasso(alpha=0.1)

In [ ]:
clf.predict([[4.0,128,6,48,13,4000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  "X does not have valid feature names, but"


array([721091.55506731])

In [ ]:
y_pred = clf.predict(X_train)
# Training Score
print("Training Accuracy:",clf.score(X_train,y_train)*100)

Training Accuracy: 13.447453391693621


In [ ]:
print("Testing Accuracy:",clf.score(X_test,y_test)*100)


Testing Accuracy: 11.582934166527759


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)

In [ ]:

print("X_test:",X_test.shape)
print("Y_test:",y_test.shape)
print("x_train:",X_train.shape)
print("y_train:",y_train.shape)

X_test: (209, 6)
Y_test: (209, 1)
x_train: (627, 6)
y_train: (627, 1)


In [ ]:
y_pred = clf.predict(X_test)
print("R^2 Score:",r2_score(y_test, y_pred)*100)

R^2 Score: 11.582934166527759


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

Mean Absolute Error: 18373.20226807193
Mean Squared Error: 1787452923.910887


In [ ]:
import numpy

In [ ]:
print('Root Mean Squared Error:', numpy.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 42278.279576052846
